package cosmoplas.comunicacion;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Documento implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Documento() {
    }

}