package cosmoplas.comunicacion;

//from row number: 1
rule "Row 1 CompraNac"
	dialect "mvel"
	when
		f1 : Documento( codBodega == "08" )
	then
		f1.setBRespJust( true );
end

//from row number: 2
rule "Row 2 CompraNac"
	dialect "mvel"
	when
		f1 : Documento( codBodega == "15" )
	then
		f1.setBRespJust( true );
end

//from row number: 3
rule "Row 3 CompraNac"
	dialect "mvel"
	when 
	    f1 : Documento( codBodega == "17" )
	then
		f1.setBRespJust( false );
end